# Generated by Django 3.0.6 on 2020-05-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preco Total'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.Categoria'),
        ),
    ]
