# Generated by Django 3.0.6 on 2020-05-28 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emprestimolivro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimolivro',
            name='data_inicial',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
