# Generated by Django 3.0.6 on 2020-05-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200528_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimolivro',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
