# Generated by Django 3.0.6 on 2020-05-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emprestimolivro_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimolivro',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
